name: CI Dev Pipeline

on:
  push:
    branches:
      - dev # S'exécute uniquement sur la branche dev

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: dev

jobs:
  # Regroupement des étapes pour garantir que l'image est disponible pour le scan et le push
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      # 1. Construction de l'image (Job 1)
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # 2. Scan de sécurité Trivy (Job 2)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'       # Bloque le pipeline si une faille est trouvée
          severity: 'CRITICAL' # Seuil de blocage imposé

      # 3. Connexion et Push vers Docker Hub (Job 3)
      - name: Login to Docker Hub
        if: success()
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image
        if: success()
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # 4. Notification par mail (Étape 5)
      - name: Send notification mail
        if: always() # S'exécute même si le scan ou le push échoue
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }} # Utilise le mot de passe d'application ici
          from: ${{ secrets.MAIL_USERNAME }}
          subject: Status Pipeline CI - Dev - ${{ github.run_number }}
          body: |
            Le pipeline pour le projet ${{ github.repository }} est terminé.
            Status final du Job : ${{ job.status }}
            Lien vers le build : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: moussawade@groupeisi.com